sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
script:
  - ([ $TRAVIS_RUST_VERSION != nightly ] || cargo test --features unstable)
  - cargo test
  - cargo test --features hyper
  - cargo build
