[package]
name = "kuchiki"
version = "0.4.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MIT"
description = "(朽木) HTML/XML tree manipulation library"
repository = "https://github.com/SimonSapin/kuchiki"

[lib]
name = "kuchiki"
doctest = false

[features]
unstable = [
    "rc/unstable",
    "html5ever/unstable",
]

[dependencies]
cssparser = "0.7"
matches = "0.1.2"
html5ever = "0.9.0"
html5ever-atoms = "0.1"
hyper = {version = ">=0.7, <0.11", optional = true}
selectors = "0.14"
rc = "0.1.0"

[dev-dependencies]
tempdir = "0.3"
